adversarial_weight: 0.001
base_channels: 128
batch_size: 8
epochs_per_stage: 150
grad_clip: 0.0
lr: 5.0e-05
mse_weight: 1.0
num_blocks: 12
num_stages: 4
num_workers: 4
optimizer: adamw
patch_size: 128
perceptual_weight: 0.1
scale_factor: 4
stage_attention: true
stage_gan: true
stage_lr_decay: 0.5
stage_transformer: true
use_gan: true
use_perceptual: true
val_freq: 1
weight_decay: 0.01
