adversarial_weight: 0.001
base_channels: 96
batch_size: 8
compile_model: true
epochs_per_stage: 5
grad_clip: 0.0
lr: 0.0002
mse_weight: 1.0
num_blocks: 6
gradient_accumulation_steps: 2
num_stages: 4
num_workers: 4
optimizer: adamw
patch_size: 128
perceptual_weight: 0.1
persistent_workers: true
pin_memory: true
prefetch_factor: 4
scale_factor: 4
stage_attention: true
stage_gan: true
stage_lr_decay: 0.5
stage_transformer: true
use_gan: false
use_mixed_precision: true
use_perceptual: false
val_freq: 1
weight_decay: 0.01
