adversarial_weight: 0.001
base_channels: 64
batch_size: 4
compile_model: false
epochs_per_stage: 50
grad_clip: 1.0
gradient_accumulation_steps: 4
lr: 0.0001
mse_weight: 1.0
num_blocks: 4
num_stages: 4
num_workers: 2
optimizer: adamw
patch_size: 64
perceptual_weight: 0.05
persistent_workers: false
pin_memory: true
prefetch_factor: 2
scale_factor: 4
stage_attention: true
stage_gan: true
stage_lr_decay: 0.7
stage_transformer: true
use_gan: true
use_mixed_precision: true
use_perceptual: false
val_freq: 1
weight_decay: 0.01
# early_stopping_enabled: true
# early_stopping_patience: 13    
# early_stopping_min_delta: 0.005
# early_stopping_monitor: psnr
# early_stopping_restore_weights: true